# Generated by Django 4.2.1 on 2023-05-11 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('number', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name_plural': 'RFIDs',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('registrationPlate', models.CharField(max_length=255, verbose_name='RegistrationPlate')),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('RFID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chargeStation.rfid')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargeStation.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='ChargeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(verbose_name='startDate')),
                ('endDate', models.DateTimeField(verbose_name='endDate')),
                ('endMeter', models.IntegerField(verbose_name='endMeter')),
                ('errorMessage', models.TextField(verbose_name='errorMessage')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chargeStation.vehicle')),
            ],
            options={
                'verbose_name_plural': 'ChargeSessions',
            },
        ),
        migrations.CreateModel(
            name='ChargePointConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('connectorNumber', models.IntegerField(default=1)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargeStation.vehicle')),
            ],
            options={
                'verbose_name_plural': 'ChargePointConnectors',
            },
        ),
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargeStation.chargepointconnector')),
            ],
            options={
                'verbose_name_plural': 'ChargePoints',
            },
        ),
    ]
