# Generated by Django 4.2.1 on 2023-05-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargeStation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargepoint',
            name='connector',
        ),
        migrations.AddField(
            model_name='chargepointconnector',
            name='chargePoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chargeStation.chargepoint'),
        ),
    ]
