# Generated by Django 4.2.1 on 2023-05-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargeStation', '0003_alter_chargesession_errormessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargesession',
            name='endDate',
        ),
    ]
