# Generated by Django 4.2.1 on 2023-05-09 03:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('connectorNumber', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'ChargePoints',
            },
        ),
        migrations.CreateModel(
            name='ChargePointConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('connectorNumber', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'ChargePointConnectors',
            },
        ),
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('number', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name_plural': 'RFIDs',
            },
        ),
    ]
