# Generated by Django 4.2.1 on 2023-05-09 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chargepoint_chargepointconnector_rfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vehicle', models.UUIDField(verbose_name='Vehicle')),
                ('startDate', models.DateTimeField(verbose_name='startDate')),
                ('endDate', models.DateTimeField(verbose_name='endDate')),
                ('errorMessage', models.TextField(verbose_name='errorMessage')),
            ],
            options={
                'verbose_name_plural': 'ChargeSessions',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('registrationPlate', models.CharField(max_length=255, verbose_name='RegistrationPlate')),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
