# Generated by Django 4.2.1 on 2023-05-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chargesession_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargePoint',
        ),
        migrations.DeleteModel(
            name='ChargePointConnector',
        ),
        migrations.DeleteModel(
            name='ChargeSession',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='RFID',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
